### ISSUE TITLE
Setting both `setEmail` and `setUserId` leads to a temp email being created

### ISSUE THREAD

**Issue by keeslinp** [Iterable/react-native-sdk#199]
I have this as part of our iterable initialization:
```
        Iterable.setEmail(email)
        Iterable.setUserId(userId)
        Iterable.trackEvent(Events.auth.signedInSessionBegan, {})
```

When I have the `setUserId` in there and look in the logs the events are mapped to a temporary email address, but if I remove that call it associates it with the email correctly. I'm not sure if this is a race condition or something. There is no feedback with `setEmail` so I can't know when it is done an "safe" to continue. Perhaps if that returned a promise I could work around this?

**Comment by davidtruong** [comment]
SetUserId does not set the userId field on the existing user profile. It actually changes the signed in user to the given userId. So since there isn't already an email associated with the userId, it will generates a new email for it.

I'm assuming you want to use the first email, then associate the userId via an user/update call. Please reach out to your CSM if you have further questions about this.

**Comment by keeslinp** [comment]
> SetUserId does not set the userId field on the existing user profile. It actually changes the signed in user to the given userId. So since there isn't already an email associated with the userId, it will generates a new email for it.
> 
> I'm assuming you want to use the first email, then associate the userId via an user/update call. Please reach out to your CSM if you have further questions about this.

Thanks for the clarification 👍
