### ISSUE TITLE
Build fails with 'Cannot Find "backgroundAlpha" in scope' error

### ISSUE THREAD

**Issue by hytea** [Iterable/react-native-sdk#89]
I am getting an error when I compile for iOS:
`node_modules/@iterable/react-native-sdk/ios/RNIterableAPI/Serialization.swift:146:35: error: cannot find 'backgroundAlpha' in scope
        dict["backgroundAlpha"] = backgroundAlpha`
![image](https://user-images.githubusercontent.com/15982991/97625526-3fe7d180-19ee-11eb-9673-89cff9d46c17.png)

- Iterable-React-Native-SDK (1.0.15)
- Iterable-iOS-SDK (6.2.14)

**Comment by roninopf** [comment]
Hi @hytea, thanks for the report. We'll fix this ASAP and make a new release.

**Comment by roninopf** [comment]
Hi @hytea , this is fixed in our latest release (1.0.18); thanks for the report! When you use the SDK, please take a look at our [iOS workaround note](https://github.com/Iterable/react-native-sdk/issues/86#issuecomment-722086119) in case it applies.

We'll close this, but if you have any further questions, please feel free to open an issue here or through your CSM/TSS.
